steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 'gcr.io/$PROJECT_ID/eye-disease-classifier:$COMMIT_SHA',
      '-t', 'gcr.io/$PROJECT_ID/eye-disease-classifier:latest',
      '.'
    ]

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/eye-disease-classifier:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/eye-disease-classifier:latest']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'eye-disease-classifier',
      '--image', 'gcr.io/$PROJECT_ID/eye-disease-classifier:$COMMIT_SHA',
      '--region', '${_REGION}',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--memory', '2Gi',
      '--cpu', '2',
      '--timeout', '300',
      '--max-instances', '10',
      '--port', '8080'
    ]

# Store images in Google Container Registry
images:
  - 'gcr.io/$PROJECT_ID/eye-disease-classifier:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/eye-disease-classifier:latest'

# Build options
options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: '100'

# Timeout for the entire build
timeout: '1200s'

# Substitutions
substitutions:
  _REGION: 'us-central1'
