name: eye-disease-classifier
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - curl
  - pip:
    # API Core
    - fastapi==0.104.1
    - uvicorn[standard]==0.24.0
    - python-multipart==0.0.6
    - pydantic>=2.0.0
    
    # ML Dependencies
    - numpy>=1.21.0
    - pillow>=9.0.0
    - tensorflow>=2.12.0
    
    # MLFlow
    - mlflow>=2.8.0
    - boto3>=1.26.0
    - psutil>=5.9.0
    - cloudpickle>=2.0.0
    
    # Utilities
    - gdown>=4.6.0
    - requests>=2.28.0
