services:
  - type: web
    name: eye-disease-classifier
    env: docker
    dockerfilePath: ./Dockerfile.mlflow
    plan: free
    region: oregon
    branch: main
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 8080
      - key: LOG_LEVEL
        value: INFO
      - key: ENABLE_MLFLOW_TRACKING
        value: false
      - key: ENVIRONMENT
        value: production
      - key: DEV_MODE
        value: true
