apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: eye-disease-classifier
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        # Configurações de recursos
        run.googleapis.com/memory: "2Gi"
        run.googleapis.com/cpu: "2"
        
        # Configurações de scaling
        autoscaling.knative.dev/maxScale: "10"
        autoscaling.knative.dev/minScale: "0"
        
        # Timeout
        run.googleapis.com/timeout: "300s"
        
        # Configurações de startup
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/startup-cpu-boost: "true"
        
    spec:
      containerConcurrency: 4
      timeoutSeconds: 300
      containers:
      - image: gcr.io/PROJECT_ID/eye-disease-classifier:latest
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: LOG_LEVEL
          value: "INFO"
        - name: ENVIRONMENT
          value: "production"
        - name: TF_CPP_MIN_LOG_LEVEL
          value: "2"
        resources:
          limits:
            memory: "2Gi"
            cpu: "2000m"
          requests:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
  traffic:
  - percent: 100
    latestRevision: true
