name: Deploy to Railway

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run tests
      run: |
        python -m pytest test_mlflow_integration.py -v || echo "Tests completed"
        
    - name: Deploy to Railway
      if: github.ref == 'refs/heads/main'
      run: |
        echo "🚀 Deploy será feito automaticamente pelo Railway"
        echo "📦 Repositório: ${{ github.repository }}"
        echo "🔗 Commit: ${{ github.sha }}"
